[font]
size = 16.0

[font.offset]
x = 0
y = 0

[font.normal]
family = "Ubuntu Mono"
style = "Regular"

[font.bold]
family = "Ubuntu Mono"
style = "Bold"

[font.italic]
family = "Ubuntu Mono"
style = "Italic"

[font.bold_italic]
family = "Ubuntu Mono"
style = "Bold Italic"

[window]
opacity = 1.0
# no titlebar/frame -- sway draws none anyway; this kills gnome's server-side deco
decorations = "None"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
